---
- :name: Avalon Yale CAS OAuth
  :provider: :cas
  :params:
    host: secure.its.yale.edu
    login_url: /cas/login
    logout_url: /cas/logout
    service_validate_url: /cas/serviceValidate
    disable_ssl_verification: true

#- :name: Avalon JSON Api
#  :id: :api
#  :tokens:
#    token:
#      :username: system_account_name
#      :email: system@example.edu
#
#- :name: Avalon Lti OAuth
#  :provider: :lti
#  :hidden: true
#  :params:
#    :oauth_credentials:
#      key: 'secret'
